#!/bin/sh

##########################################################################
#                                                                        #
#                 *************************************                  #
#                 * Copyright 2019 Federico Cosentino *                  #
#                 *************************************                  #
#                                                                        #
# This program is free software: you can redistribute it and/or modify   #
# it under the terms of the GNU General Public License as published by   #
# the Free Software Foundation, either version 3 of the License, or      #
# (at your option) any later version.                                    #
#                                                                        #
# This program is distributed in the hope that it will be useful,        #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU General Public License      #
# along with this program.  If not, see <https://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

ip="/sbin/ip"
brctl="/usr/sbin/brctl"
bridges_list="/etc/net_bridges.txt"

# If config is not present exit immediately
[ -f "$bridges_list" ] || exit 0

start() {
	printf "Create network bridges: "

	while read -r line ; do
		# Ignore comments and blank lines.
		case "$line" in
			""|"#"*) continue ;;
		esac

		bridge=$(echo $line | awk '{print $1}')
		interfaces=$(echo $line | awk '{for (i=2; i<=NF; i++) printf "%s ", $i; print ""}')

		# Create the bridge
		$brctl addbr $bridge

		# Add the intefaces to the bridge and bring them up
		for iface in $interfaces ; do
			$brctl addif $bridge $iface
			$ip l set $iface up
		done

	done < "$bridges_list" 

	echo "OK"
}
stop() {
	printf "Delete the bridge $dev: "

	while read -r line ; do
		# Ignore comments and blank lines.
		case "$line" in
			""|"#"*) continue ;;
		esac

		bridge=$(echo $line | awk '{print $1}')
		interfaces=$(echo $line | awk '{for (i=2; i<=NF; i++) printf "%s ", $i; print ""}')

		# Bring down the interfaces and remove them from the bridge
		for iface in $interfaces ; do
			$ip l set $iface down
			$brctl delif $bridge $iface
		done

		# Delete the bridge
		$brctl delbr $bridge

	done < "$bridges_list" 

	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
