#!/bin/sh

##########################################################################
#                                                                        #
#                 *************************************                  #
#                 * Copyright 2019 Federico Cosentino *                  #
#                 *************************************                  #
#                                                                        #
# This program is free software: you can redistribute it and/or modify   #
# it under the terms of the GNU General Public License as published by   #
# the Free Software Foundation, either version 3 of the License, or      #
# (at your option) any later version.                                    #
#                                                                        #
# This program is distributed in the hope that it will be useful,        #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU General Public License      #
# along with this program.  If not, see <https://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

dev="br0"
address="10.0.1.1/24"
broadcast="10.0.1.255"
gateway="10.0.1.1"

ifaces="eth0 usb0" # wlan0 is added by hostapd

ip="/sbin/ip"
brctl="/usr/sbin/brctl"

start() {
	printf "Create the bridge $dev: "

	# Create the bridge
	$brctl addbr $dev

	# Add the intefaces to the bridge
	for iface in $ifaces ; do
		$brctl addif $dev $iface
	done

	# Configure the bridge
	$ip addr add $address broadcast $broadcast dev $dev label $dev

	# Bring up the interfaces
	for iface in $ifaces ; do
		$ip link set $iface up
	done
	$ip link set $dev up

	# Set the default route
	$ip route add default via $gateway dev $dev

	echo "OK"
}
stop() {
	printf "Delete the bridge $dev: "

	# Delete the default route
	$ip route del default via $gateway dev $dev

	# Bring down the interfaces
	$ip link set $dev down
	for iface in $ifaces ; do
		$ip link set $iface down
	done

	# Delete the configuration of the bridge
	$ip addr del $address broadcast $broadcast dev $dev label $dev

	# Remove the interfaces from the bridge
	for iface in $ifaces ; do
		$brctl delif $dev $iface
	done

	# Delete the bridge
	$brctl delbr $dev

	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
