#!/bin/sh

# Script copied and adapted from S80dnsmasq

# Check if hostapd config file is present
[ -f /etc/hostapd.conf ] || exit 0

start() {
	printf "Starting hostapd: "
	/usr/sbin/hostapd -B /etc/hostapd.conf
	echo "OK"
}
stop() {
	printf "Stopping hostapd: "
	killall hostapd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
