#!/bin/sh

##########################################################################
#                                                                        #
#                 *************************************                  #
#                 * Copyright 2019 Federico Cosentino *                  #
#                 *************************************                  #
#                                                                        #
# This program is free software: you can redistribute it and/or modify   #
# it under the terms of the GNU General Public License as published by   #
# the Free Software Foundation, either version 3 of the License, or      #
# (at your option) any later version.                                    #
#                                                                        #
# This program is distributed in the hope that it will be useful,        #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU General Public License      #
# along with this program.  If not, see <https://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

# Global activation of the nat/firewall script
GlobalEnable=false

#####################
# NAT configuration #
#####################

EnableNat=false # Enable NAT translation

ExternalDev="" # Mandatory variable
ExternalIP="" # If set it uses SNAT as target, it not it uses MASQUERADE

InternalDev="br0" # Mandatory variable
InternalNet="192.168.1.0/24" # Mandatory variable

############
# Firewall #
############

EnableFirewall=false
AllowICMP=true
